name: CI/CD Pipeline for Product CRUD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Ajusta según la versión de Java que necesites

      - name: Build Project
        run: ./mvnw clean install # Ajusta si usas otro sistema de construcción

      - name: Run Tests
        run: ./mvnw test # Ajusta si usas otro comando de prueba

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging server..."
          # Aquí debes añadir el comando o script de despliegue
          # Ejemplo: ./deploy.sh
        env:
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}

      - name: Notify Deployment
        run: |
          echo "Notifying deployment status"
          # Agrega aquí el comando para notificar el estado del despliegue
